#!/usr/bin/env node

# Tab-name aliases config

#!/bin/bash
alias tab-name="~/.config/i3/rename"
alias tab-rename="~/.config/i3/i3-workspacer.py rename -na"

alias tab-name-browser="tab-rename "
tab_name_browser="tab-rename "

alias tab-name-term="tab-rename "   
tab_name_term="tab-rename "   

alias tab-name-torrent="tab-rename "
tab_name_torrent="tab-rename "

alias tab-name-paint="tab-rename "
tab_name_paint="tab-rename "

alias tab-name-music="tab-rename "
tab_name_music="tab-rename "

alias tab-name-files="tab-rename "
tab_name_files="tab-rename "

alias tab-name-word="tab-rename "
tab_name_word="tab-rename "

alias tab-name-powerpoint="tab-rename "
tab_name_powerpoint="tab-rename "

alias tab-name-letter="tab-rename "
tab_name_letter="tab-rename "

alias tab-name-cheat="firefox ~/.config/i3/icons-cheat.html"
