#!/bin/bash

browser=
web=
net=
firefox=
chrome=
chromium=
luakit=

terminal=
term=
shell=

images=

torrent=

paint=

music=
cmus=
moc=
ncmpcpp=
mpd=
ncmpc=

files=

word=

powerpoint=

letter=

lock=
secure=
sec=

develop=
devel=
dev=

gaming=
game=

vkontakte=
vk=

youtube=
yt=

fix=

git=

github=

linux=

phone=

book=
manual=
man=

server=
serv=

film=

save=

settings=

telegram=

math=
maths=

upload=

usb=

user=

camera=

check=
checked=

code=

fork=

dropbox=

warning=
warn=

watch=

flag=

wifi=
wireless=

keys=
keyboard=

map=

microphone=
phone=

qrcode=
qr=

question=

info=
information=

star=

record=

magic=

write=
pen=

numofworkspace=$(i3-msg -t 'get_workspaces' | sed -e 's/{"num/\n{"num/g' | grep \"focused\":true | sed -e 's/,"/\n/g' | grep name | cut -d\" -f 3 | grep -o '[0-9]0*')

symbolofworkspace=$(eval "echo $"$1"")

i3-msg "rename workspace to \"$numofworkspace: $symbolofworkspace\""
