#!/bin/bash

# Tab-name aliases config

alias tab-name="~/.config/i3/rename"
alias tab-name-browser="tab-name "
alias tab-name-term="tab-name "   
alias tab-name-torrent="tab-name " 
alias tab-name-music="tab-name "
alias tab-name-cheat="firefox ~/.config/i3/icons-cheat.html"
