// Generated by CoffeeScript 1.12.5
(function() {
  var childProcess, ex, exec, log, program;
  program = require("commander");
  program.version('0.0.1').option('-s, --symbol [symbol]', 'name of symbol').parse(process.argv);
  childProcess = require("child_process");
  exec = childProcess.exec;
  ex = module.exports;
  log = console.log;
  ex.toTable = function(str) {
    var i, len, m, m2, m3, t;
    m = str.split("; ");
    m3 = [];
    for (i = 0, len = m.length; i < len; i++) {
      m2 = m[i];
      t = m2.split(": ");
      m3[t[0]] = t[1];
    }
    return m3;
  };
  ex.table = ex.toTable("browser: ; term: ; torrent: ; paint: ; music: ; files: ; word: ; powerpoint: ; letter: ");
  ex.rename = function(name) {
    return exec(__dirname + "/i3-workspacer.py rename -na " + ex.table[name]);
  };
  return (function() {
    if (program.symbol) {
      ex.rename(program.symbol);
      return log("Symbol of workspace was changed to " + ex.table[program.symbol]);
    }
  })();
})();
