// Generated by CoffeeScript 1.12.5
var cmus, log, remote, str;

cmus = require('cmus-remote-node');

log = console.log;

remote = new cmus();

str = '';

remote.status(function(status) {
  if (status && status.status !== 'stopped') {
    str += status.track.artist + ' - ' + status.track.title + ' ';
    if (status.status === 'playing') {
      str += '  ';
    }
    if (status.status === 'paused') {
      str += '  ';
    }
    if (status.settings.repeat_current) {
      str += '  ';
    }
    log(str);
  }
  return process.exit();
});
