#!/bin/bash

echo lol | rofi -dmenu -kb-clear-line &
sleep 1
pkill rofi
echo kek | rofi -dmenu -kb-clear-line &
sleep 1
pkill rofi
echo lol | rofi -dmenu -kb-clear-line &
sleep 1
pkill rofi
echo kek | rofi -dmenu -kb-clear-line &
sleep 1
pkill rofi