#!/bin/bash

w1=$(i3-msg -t 'get_workspaces' | jq -r '.[0].name')
w2=$(i3-msg -t 'get_workspaces' | jq -r '.[1].name')
w3=$(i3-msg -t 'get_workspaces' | jq -r '.[2].name')
w4=$(i3-msg -t 'get_workspaces' | jq -r '.[3].name')
w5=$(i3-msg -t 'get_workspaces' | jq -r '.[4].name')
w6=$(i3-msg -t 'get_workspaces' | jq -r '.[5].name')
w7=$(i3-msg -t 'get_workspaces' | jq -r '.[6].name')
w8=$(i3-msg -t 'get_workspaces' | jq -r '.[7].name')
w9=$(i3-msg -t 'get_workspaces' | jq -r '.[8].name')
w10=$(i3-msg -t 'get_workspaces' | jq -r '.[9].name')
