#!/bin/bash

pkill lemonbar

while true
do
	if ! [[ $(pgrep lemonbar) ]]
	then
		break
	fi
done

#conky -q | lemonbar -b -f "xos4 Terminus:pixelsize=12" -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1'
conky -q -u 5 | lemonbar -b -f '-*-tewi2a-medium-r-normal-*-11-*-*-*-*-*-*-1' -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1'
