#!/bin/bash

if [[ $1 == "1" ]]
then
	urxvt -e ~/.config/i3/widgets/alsa-wm &>> /dev/null
	amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1
else
	amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1
fi
