#!/bin/bash

if [[ $1 == "1" ]]
then
	echo $BLOCK_X > ~/.config/i3/widget-x
	~/.config/i3/termites/alsa-wm -c ~/.config/termite/status  -e ~/.config/i3/widgets/alsa-wm &>> /dev/null
	amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1
else
	amixer get Master | grep -E -o '[0-9]{1,3}?%' | head -1
fi
