#!/bin/bash

if [[ $1 == "1" ]]
then
	echo $BLOCK_X > ~/.config/i3/widget-x
	~/.config/i3/termites/cpu-wm -c ~/.config/termite/status -e ~/.config/i3/widgets/cpu-wm &>> /dev/null
	~/.config/i3/scripts/cpu_usage
else
	~/.config/i3/scripts/cpu_usage
fi
