#!/bin/bash

if [[ $1 == "1" ]]
then
	echo $BLOCK_X > ~/.config/i3/widget-x
	~/.config/i3/termites/df-wm -c ~/.config/termite/status -e ~/.config/i3/widgets/df-wm &>> /dev/null
	~/.config/i3/scripts/disk
else
	~/.config/i3/scripts/disk
fi
