#!/bin/bash

if [[ $(mpc | sed -n 2p) != "" ]]
then
	if [[ $1 == "1" ]]
	then
		echo $BLOCK_X > ~/.config/i3/widget-x
		~/.config/i3/termites/mpd-wm -c ~/.config/termite/status -c ~/.config/termite/status -e ~/.config/i3/widgets/mpd-wm &>> /dev/null
		mpc | head -1
	else
		mpc | head -1
	fi
fi
